TankGame:
<TankGame@BoxLayout>:
    size:root.size
    Label:
        text:'TANK CRAFT'

<TankWidget>:
    width:40
    height:40
    canvas:
        Rectangle:
            pos:self.size[0]/2-20,self.size[1]/2-12.5
            size:40,25

        Rectangle:
            pos:self.size[0]/2-2.5,self.size[1]/2+12.5
            size:5,15

<BulletWidget>:
    width:25
    height:25
    canvas:
        Rectangle:
            pos:0,0
            size:20,20