TankGame:
<TankGame@RelativeLayout>:
    size:root.size
    Label:
        text:'TANK CRAFT'

<TankWidget>:
    width:40
    height:40
    canvas:
        Rectangle:
            pos:self.pos_x,self.pos_y
            size:40,25

        Rectangle:
            pos:self.pos_x,self.pos_y
            size:5,15

<BulletWidget>:
    width:4
    height:4
    canvas:
        Ellipse:
            pos:self.pos_x,self.pos_y
            size:4,4